@BASE_URL = http://localhost:3000

### Create a new user
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "Muskan Doe",
    "email": "muskan.doe@example.com",
    "password": "password"
}

### Get all users
GET {{BASE_URL}}/users

### Get user by id
GET {{BASE_URL}}/users/691af6ce679594af902955ef


### Update user by id
PATCH {{BASE_URL}}/users/691b00adc7abc32e2e5f4044
Content-Type: application/json

{
    "email": "jack.doe@example.com"
}

### Delete user by id
DELETE {{BASE_URL}}/users/691b00adc7abc32e2e5f4044